### ISSUE TITLE
微信支付异步通知，无法使用wxpay.isPayResultNotifySignatureValid(notifyMap) 进行HMAC-SHA-256验签

### ISSUE THREAD

**Issue by berticoix** [wxpay/WXPay-SDK-Java#1]
看了一下WXPay里的代码  
 public boolean isPayResultNotifySignatureValid(Map<String, String> reqData) throws Exception {
        String signTypeInData = reqData.get(WXPayConstants.FIELD_SIGN_TYPE);
        SignType signType;
        if (signTypeInData == null) {
            signType = SignType.MD5;
        }
        else {
            signTypeInData = signTypeInData.trim();
            if (signTypeInData.length() == 0) {
                signType = SignType.MD5;
            }
            else if (WXPayConstants.MD5.equals(signTypeInData)) {
                signType = SignType.MD5;
            }
            else if (WXPayConstants.HMACSHA256.equals(signTypeInData)) {
                signType = SignType.HMACSHA256;
            }
            else {
                throw new Exception(String.format("Unsupported sign_type: %s", signTypeInData));
            }
        }
        return WXPayUtil.isSignatureValid(reqData, this.config.getKey(), signType);
    }

里面的signtype 取自通知的xml里的sign_type 但是通知里没有sign_type，所以一直默认MD5进行验证，如果加密用的SHA256就会一直验签失败。
用 WXPay wxpay = new WXPay(config, WXPayConstants.SignType.HMACSHA256);这个进行验签也是这个结果

**Comment by letiantian** [comment]
这里应该没有问题，支付结果通知的签名就是xml消息里指定的，没有的话是MD5，有signtype的话才可能是才可能是HMACSHA256。

```
WXPay wxpay = new WXPay(config, WXPayConstants.SignType.HMACSHA256);
```
上面的签名用于商户发起的请求生成签名和返回数据的验证签名。

**Comment by llsi4275** [comment]
@letiantian 

我也有同样的问题：
在发起支付时，使用的是**HMAC-SHA256**签名方式，但是收到的支付通知数据中**没有**sign_type参数，支付通知中的数据签名又是HMAC-SHA256签名，使用isPayResultNotifySignatureValid接口直接就歇菜了。。。

**Comment by letiantian** [comment]
那就是这个接口有问题了。先别用这个借口，直接用
```
WXPayUtil.isSignatureValid(reqData, this.config.getKey(), signType);
```
